/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmsoft.Formularios;

import dmsoft.Clases.Entidades.Empleados;
import dmsoft.Clases.Entidades.Producto;
import dmsoft.Clases.Entidades.Roles;
import dmsoft.Clases.Entidades.Utilidades;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany_Hernandez
 */
public class IframeProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeEmpleados
     * @param dimension
     */
    //Creamos objetos para los modelos de nuestra tablas
    DefaultTableModel modeloProductos;
    //Creamos un objeto de la clase Usuarios para usarlo
    Roles usuario=new Roles();

    Utilidades utilidades=new Utilidades();
    private int tipoOperacion=Utilidades.DEFAULT;
   Producto producto=new Producto();
    
    //Creamos un formato para la fecha en sql
    SimpleDateFormat formatoFecha=new SimpleDateFormat("yyyy-MM-dd");
    
    public IframeProductos() {
        initComponents();
        
      //Eliminamos el border del JInternalFrame para que no nos muestre las opciones de arriba
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI(); 
        bi.setNorthPane(null);

        

        modeloTabla();

        //Una ves que hemos creado el modelo aho le damos formato a la table
        formatoTabla();
                   
        //llamamos este metodo para que nos muestre el panel de empleados
        utilidades.cambiarComponente(tbneProductos, panelProductos, "Empleados");
        //Cambiamos el header de la tabla
        producto.obtenerDatos(tblProductos, modeloProductos, "Todos", "");
       //Llenamos los combobox para poder visualizar todo lo que hemos guardado
        producto.obtenerCategoria(cbxCategoria);
        producto.obtenerProveedor(cbxProveedor);
        producto.obtenerUnidad(cbxMedida);
        //Reseteamos la varibale change ya que en el metodo obtenerTipoUsuarios se vuelve positiva
         utilidades.setChanged(false);
         btnRetornar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        tbneProductos = new javax.swing.JTabbedPane();
        panelProductos = new javax.swing.JPanel();
        spneTablaEmpleados = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        panelBuscarEmpleado = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cboFiltroEmpleados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelDatos = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spneTxtDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtaInstrucciones = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbxMedida = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblWarningPrecio = new javax.swing.JLabel();
        txtPrecion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtIsv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblWarningImpuesto = new javax.swing.JLabel();
        lblWarningCantidad = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setBorder(null);
        setName("Productos"); // NOI18N

        tbneProductos.setBackground(new java.awt.Color(252, 252, 252));
        tbneProductos.setForeground(new java.awt.Color(51, 51, 51));
        tbneProductos.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tbneProductos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tbneProductos.setOpaque(true);
        tbneProductos.setPreferredSize(new java.awt.Dimension(750, 340));

        panelProductos.setLayout(new java.awt.BorderLayout(0, 5));

        tblProductos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tblProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblProductos.setOpaque(false);
        tblProductos.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tblProductos.setSelectionForeground(new java.awt.Color(226, 226, 226));
        spneTablaEmpleados.setViewportView(tblProductos);

        panelProductos.add(spneTablaEmpleados, java.awt.BorderLayout.CENTER);

        panelBuscarEmpleado.setBackground(new java.awt.Color(246, 246, 246));
        panelBuscarEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 216, 216)));
        panelBuscarEmpleado.setPreferredSize(new java.awt.Dimension(100, 90));
        panelBuscarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(61, 61, 61));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Buscar");
        panelBuscarEmpleado.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 27));

        txtBuscarProducto.setBackground(new java.awt.Color(252, 252, 252));
        txtBuscarProducto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(30, 30, 30));
        txtBuscarProducto.setToolTipText("");
        txtBuscarProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });
        panelBuscarEmpleado.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 450, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(61, 61, 61));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Mostrar");
        panelBuscarEmpleado.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 410, 27));

        cboFiltroEmpleados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        cboFiltroEmpleados.setForeground(new java.awt.Color(30, 30, 30));
        cboFiltroEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los productos", "Solo los empleados activos", "Solo los empleados inactivos" }));
        cboFiltroEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltroEmpleadosActionPerformed(evt);
            }
        });
        panelBuscarEmpleado.add(cboFiltroEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 300, 30));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Puede filtrar los productos de acuerdo a su estado, y  puede realizar una busqueda por cualquiera de los     campos que aparecen en la tabla");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        panelBuscarEmpleado.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 15, 330, 60));

        panelProductos.add(panelBuscarEmpleado, java.awt.BorderLayout.NORTH);

        tbneProductos.addTab("Productos", panelProductos);

        panelDatos.setBackground(new java.awt.Color(250, 250, 250));
        panelDatos.setPreferredSize(new java.awt.Dimension(600, 400));
        panelDatos.setLayout(new java.awt.GridBagLayout());

        pnlDatos.setBackground(new java.awt.Color(246, 246, 246));
        pnlDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        pnlDatos.setForeground(new java.awt.Color(204, 204, 204));
        pnlDatos.setPreferredSize(new java.awt.Dimension(702, 140));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 61, 61));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código de barra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel1, gridBagConstraints);

        txtCodigo.setBackground(new java.awt.Color(252, 252, 252));
        txtCodigo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(30, 30, 30));
        txtCodigo.setAutoscrolls(false);
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(txtCodigo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 61, 61));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel2, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(30, 30, 30));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(txtNombre, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(61, 61, 61));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Descripcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel10, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("*");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setPreferredSize(new java.awt.Dimension(8, 8));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 150);
        pnlDatos.add(jLabel14, gridBagConstraints);

        jLabel18.setBackground(new java.awt.Color(151, 196, 242));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/productos26.png"))); // NOI18N
        jLabel18.setText("Información del producto");
        jLabel18.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 46;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlDatos.add(jLabel18, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("*");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 150);
        pnlDatos.add(jLabel15, gridBagConstraints);

        spneTxtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        txtDescripcion.setBackground(new java.awt.Color(252, 252, 252));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(30, 30, 30));
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(2);
        txtDescripcion.setToolTipText("");
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        spneTxtDescripcion.setViewportView(txtDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(spneTxtDescripcion, gridBagConstraints);

        txtaInstrucciones.setEditable(false);
        txtaInstrucciones.setBackground(new java.awt.Color(246, 246, 246));
        txtaInstrucciones.setColumns(23);
        txtaInstrucciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtaInstrucciones.setForeground(new java.awt.Color(137, 137, 135));
        txtaInstrucciones.setLineWrap(true);
        txtaInstrucciones.setRows(3);
        txtaInstrucciones.setTabSize(10);
        txtaInstrucciones.setText("Cuando se guarda un producto este debe tener por lo menos tres datos básicos, Código, Nombre y Precio y así puedas utilizarlo cuando factures, ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 39, 10, 27);
        pnlDatos.add(txtaInstrucciones, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel22, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel24, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Impuesto Sobre Venta (ISV)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel25, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Medida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 0, 19);
        pnlDatos.add(jLabel26, gridBagConstraints);

        cbxMedida.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxMedida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMedidaItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(cbxMedida, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel27, gridBagConstraints);

        cbxProveedor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProveedorItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(cbxProveedor, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 19);
        pnlDatos.add(jLabel28, gridBagConstraints);

        cbxCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCategoriaItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(cbxCategoria, gridBagConstraints);

        cbxEstado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEstadoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 24);
        pnlDatos.add(cbxEstado, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 20, 19);
        pnlDatos.add(jLabel3, gridBagConstraints);

        lblWarningPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWarningPrecio.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarningPrecio.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 150);
        pnlDatos.add(lblWarningPrecio, gridBagConstraints);

        txtPrecion.setBackground(new java.awt.Color(252, 252, 252));
        txtPrecion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtPrecion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtPrecion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecionKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(txtPrecion, gridBagConstraints);

        txtCantidad.setBackground(new java.awt.Color(252, 252, 252));
        txtCantidad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 21);
        pnlDatos.add(txtCantidad, gridBagConstraints);

        txtIsv.setBackground(new java.awt.Color(252, 252, 252));
        txtIsv.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtIsv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtIsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIsvKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlDatos.add(txtIsv, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 24);
        pnlDatos.add(jLabel5, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/productosLogo128.png"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 26);
        pnlDatos.add(jLabel6, gridBagConstraints);

        lblWarningImpuesto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        lblWarningImpuesto.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlDatos.add(lblWarningImpuesto, gridBagConstraints);

        lblWarningCantidad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        lblWarningCantidad.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlDatos.add(lblWarningCantidad, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.gridheight = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 202;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 70, 15, 32);
        panelDatos.add(pnlDatos, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*  Campos obligatarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 60, 13, 0);
        panelDatos.add(jLabel19, gridBagConstraints);

        tbneProductos.addTab("Agregar", panelDatos);

        getContentPane().add(tbneProductos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(250, 250, 250));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        panelBotones.setPreferredSize(new java.awt.Dimension(120, 23));
        panelBotones.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        btnNuevo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregarDatos40.png"))); // NOI18N
        btnNuevo.setText("Nuevo producto");
        btnNuevo.setToolTipText("Agregar nuevo empleado");
        btnNuevo.setBorder(null);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFocusPainted(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setPreferredSize(new java.awt.Dimension(70, 75));
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregarDatos44.png"))); // NOI18N
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelBotones.add(btnNuevo);

        btnGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar40.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar empleado");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar44.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar40.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita un empleado");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar44.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEditar);

        btnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/return40.png"))); // NOI18N
        btnRetornar.setText("Regresar");
        btnRetornar.setToolTipText("Sale de la pestaña");
        btnRetornar.setBorderPainted(false);
        btnRetornar.setContentAreaFilled(false);
        btnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetornar.setFocusPainted(false);
        btnRetornar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetornar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnRetornar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/return44.png"))); // NOI18N
        btnRetornar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        panelBotones.add(btnRetornar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboFiltroEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltroEmpleadosActionPerformed

 producto.obtenerDatos(tblProductos, modeloProductos, getFiltro(cboFiltroEmpleados.getSelectedIndex()), txtBuscarProducto.getText());
        
    }//GEN-LAST:event_cboFiltroEmpleadosActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      //Validamos que no se este realizando ninguna otra operacion y que la operacion sea por DEFAULT
       if(tipoOperacion==Utilidades.DEFAULT)
       {
          //Validamos que se haya seleccionado un producto de la tabla
           if(tblProductos.getSelectedRow()>=0)
           {
               //Cambiamos el tipo de operacion
               tipoOperacion=Utilidades.EDITAR;
                btnRetornar.setVisible(true);
                
               //Consultamos todos los datos del producto a la base de datos por medio de su cedula
               //Este metodo llenara las variables de la clase empleados
               producto.obtenerDatos(tblProductos.getValueAt(tblProductos.getSelectedRow(),0).toString());
                
               //Accedemos a las variables por medio de los metodos get y las asignamos a los campos
                getDatos();   
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Seleccione un empleado de la tabla");
           }
       }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
       int opcion;
        if(utilidades.isChanged())
        {
              opcion=JOptionPane.showConfirmDialog(null,"Los datos se modificaron.\n"
                                           + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
              if(opcion==JOptionPane.YES_OPTION)
              {
                  if(guardarDatos())
                  {
                      btnRetornar.setVisible(false);
                      resetFields();
                      utilidades.cambiarComponente(tbneProductos, panelProductos, "Pruductos");
                  }
              }
              else if(opcion==JOptionPane.NO_OPTION)
              {
                  //Reseteamos la operacion a default
                  btnRetornar.setVisible(false);
                  resetFields();
                  utilidades.cambiarComponente(tbneProductos, panelProductos, "Productos");
                  
              }
                  
        }
        else
        {
            //Reseteamos la operacion a default
                 btnRetornar.setVisible(false);
                  resetFields();
                 utilidades.cambiarComponente(tbneProductos, panelProductos, "Productos");
        }
           
            
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

   if(!utilidades.isChanged())
    {
         tipoOperacion=Utilidades.NUEVO;
         btnRetornar.setVisible(true);
         utilidades.cambiarComponente(tbneProductos, panelDatos, "Crear un producto nuevo");
    }
    else
    {
        int opcion=JOptionPane.showConfirmDialog(null,"Los datos se modificaron.\n"
                                           + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opcion==JOptionPane.YES_OPTION)
         {
                if(guardarDatos())
                {
                  resetFields();
                  utilidades.cambiarComponente(tbneProductos, panelDatos, "Crear un producto nuevo");
                }
                  
              }
              else if(opcion==JOptionPane.NO_OPTION)
              {
                  //Reseteamos la operacion a default
                  resetFields();
                  utilidades.cambiarComponente(tbneProductos, panelDatos, "Crear un producto nuevo");
              }
    }
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(tipoOperacion==Utilidades.NUEVO||tipoOperacion==Utilidades.EDITAR)
        {
             if(guardarDatos())
             {
                utilidades.cambiarComponente(tbneProductos, panelProductos, "Productos");
                producto.obtenerDatos(tblProductos, modeloProductos, "Todos", "");
                btnRetornar.setVisible(false);
             }
             
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
     producto.obtenerDatos(tblProductos, modeloProductos, getFiltro(cboFiltroEmpleados.getSelectedIndex()), txtBuscarProducto.getText());
        
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void txtPrecionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecionKeyReleased
          utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtPrecionKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
     utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtIsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsvKeyReleased
         utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtIsvKeyReleased

    private void cbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCategoriaItemStateChanged
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxCategoriaItemStateChanged

    private void cbxProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProveedorItemStateChanged
      utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxProveedorItemStateChanged

    private void cbxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEstadoItemStateChanged
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxEstadoItemStateChanged

    private void cbxMedidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMedidaItemStateChanged
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxMedidaItemStateChanged
     
    //Este metodo es para darle diseño al modelo de la tabla 
   private  void modeloTabla(){
      //Creamos un arreglo de Strings para los encabezados de nuestra tabla
    String encabezados[]= {"Codigo", "Nombre", "Disponible", "Precio", 
                           "ISV", "Proveedor", "Descripción",
                              "Estado"};
    //Creamos un modelo para nuestros arreglo para los encabezados
   modeloProductos=new DefaultTableModel(null,encabezados){
           /*Creamos un arreglo de tipos para nuestra tabla, dicho arreglo es paralelo con el nombre 
        arreglo de nombres del encabezado*/
        Class tipos[]={
                Object.class,
                String.class, 
                String.class,
                String.class,
                String.class,
                String.class,
                String.class,
                String.class};
        //Sobre escribimos el metodo getColumIndex para que devuelva la posicion de nuestro arreglo de tipos
        @Override
         public Class getColumnClass(int index){
            return tipos[index];
         }
         
       
       
         //Tambien sobre escribimos el metodo que permite editar las celdas de la tabla
        @Override
         public boolean isCellEditable(int rowIndex,int columnIndex){
             return false;
         }
       };
    //Agregamos nuestro modelo a la tabla
      tblProductos.setModel(modeloProductos);
     }
    
    
    //Este metodo se encarga del diseño de la tabla, es decir del formato de las celdas
    private void formatoTabla()
    {
       int codigo=130,
           nombre=200,
           cantidad=130,
           precio=120,
           isv=50,
           proveedor=250,
           descripcion=300,
           estado=70;
           
      //Creamos un arreglo con las medidas fijos predeterminados de la tabla para cada celda
      int ancho[]={codigo,nombre,cantidad,precio,isv,proveedor,descripcion,estado};
      for(int i=0;i<tblProductos.getColumnCount();i++)
      {
          tblProductos.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
          tblProductos.getColumnModel().getColumn(i).setResizable(false);
      }
      tblProductos.setRowHeight(20);
      //Establecemos el header
      new Utilidades().setTableHeader(tblProductos);
    }
   

    //Este metodo se encarga de deicidir que tipo de operacion se realizara. Si es Guardar o Actualizar
   private boolean realizarOperacion(int tipo){
       boolean realizado=false;
       switch(tipo)
       {
            case Utilidades.NUEVO:
                //llenamos la variables de la clase empleados con los valores del campo de texto
                //que luego seran enviadas en el metodo guardar o actualizar
                setDatos();
                //Luego utilizamos las variables para mandar a llamar al metodo guardar
                 if(producto.guardar())
                  realizado=true;  
            break;
            case Utilidades.EDITAR:
                setDatos();
               if(producto.actualizar())
                   realizado=true;
            break;
       }
       return realizado;
   }

   //Con este metodo obtenemos todos los valores de los campos
   private void setDatos()
   {
     producto.setCodigo(txtCodigo.getText());
     producto.setNombre(txtNombre.getText());
     producto.setPrecio(Float.parseFloat(txtPrecion.getText()));
     producto.setDescripcion(txtDescripcion.getText());
     producto.setCantidad(Float.parseFloat(txtCantidad.getText()));
     producto.setUnidad(cbxMedida.getSelectedItem().toString());
     producto.setIsv(Float.parseFloat(txtIsv.getText()));
     producto.setCategoria(cbxCategoria.getSelectedItem().toString());
     producto.setProveedor(cbxProveedor.getSelectedItem().toString());
     producto.setEstado(cbxEstado.getSelectedItem().toString());
     
   }
   
   //Con este metodo asignamos los valores a las variables a los campos 
   private void  getDatos()
   {
      
       utilidades.cambiarComponente(tbneProductos, panelDatos, "Editar datos del empleado");
       txtCodigo.setText(String.valueOf(producto.getCodigo()));
       txtNombre.setText(producto.getNombre());
       txtPrecion.setText(String.valueOf(producto.getPrecio()));
       txtDescripcion.setText(producto.getDescripcion());
       txtCantidad.setText(String.valueOf(producto.getCantidad()));
       txtIsv.setText(String.valueOf(producto.getIsv()));
       cbxMedida.setSelectedItem(producto.getUnidad());
       cbxCategoria.setSelectedItem(producto.getCategoria());
       cbxProveedor.setSelectedItem(producto.getProveedor());
       cbxEstado.setSelectedItem(producto.getEstado());
//       cbxTipoUsuario.setSelectedItem(producto.getTipoUsuario());
       /*Debido a que los combobox tiene implementa el ItemListener cada vez que seleccionamos, un item
        el envento detecta el cambio y marca la varible change como true, entonces cada vez que se hace 
       una seleccion en los comboBox entonces la reseteamos porque no es un cambio que nosotros hacemos*/
       utilidades.setChanged(false);
   }
   
   //Con este metodo vamos a limpiar los campos
   private void resetFields()
   {
       tipoOperacion=Utilidades.DEFAULT;
         txtCodigo.setText("");
         txtNombre.setText("");
         txtPrecion.setText("0");
         txtDescripcion.setText("");
         txtCantidad.setText("0");
         txtIsv.setText("0");
         cbxMedida.setSelectedIndex(0);
         cbxEstado.setSelectedIndex(0);
         cbxCategoria.setSelectedIndex(0);
         cbxProveedor.setSelectedIndex(0);
         txtBuscarProducto.setText("");
         cboFiltroEmpleados.setSelectedIndex(0);
       /*Debido a que los combobox implementan la Interfaz ItemListener cada vez que se selecciona  o agrega .
         un item el envento detecta el cambio y cambia el valor de la varible "change" a true, pare evitar esto
        cada vez que se hace una seleccion en los comboBox desde codigo la reseteamos porque no es un cambio que
         el usuario a realizado*/
       utilidades.setChanged(false);
     
   }
   
   private boolean guardarDatos(){
       boolean realizado=false;
       //Validamos los campos obligatorios
        if(!utilidades.validarCampos(txtNombre.getText(),txtCodigo.getText(),txtPrecion.getText()))
            {
                //LLamamos la funcion realizarOperacion para que defina si esta guardando o actualizando
               if(realizarOperacion(tipoOperacion))
               {
                  resetFields();
//                  producto.obtenerDatos(tblEmpleados, modeloProductos, "Todos", "");
                  realizado=true;
               }
                  
            }
            else
              JOptionPane.showMessageDialog(null,"Campos obligatorios vacios");
        return realizado;
   }
   
   private String getFiltro(int index)
   {
       String filtro="";
        switch (index) {
            case 0:
                filtro="Todos";
                break;
            case 1:
                filtro="Activo";
                break;
            case 2:
                filtro="Inactivo";
                break;
            default:
                break;
        }
       return filtro;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRetornar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboFiltroEmpleados;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxMedida;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblWarningCantidad;
    private javax.swing.JLabel lblWarningImpuesto;
    private javax.swing.JLabel lblWarningPrecio;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscarEmpleado;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JScrollPane spneTablaEmpleados;
    private javax.swing.JScrollPane spneTxtDescripcion;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTabbedPane tbneProductos;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIsv;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecion;
    private javax.swing.JTextArea txtaInstrucciones;
    // End of variables declaration//GEN-END:variables
}
