/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmsoft.Formularios;

import dmsoft.Clases.Entidades.Categoria;
import dmsoft.Clases.Entidades.Proveedor;
import dmsoft.Clases.Entidades.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany_Hernandez
 */
public class IframeCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeCategoria
     */
    int tipoOperacion=Utilidades.NUEVO;
    Utilidades utilidades=new Utilidades();
    DefaultTableModel modeloCategoria;
    Categoria categoria=new Categoria();
    
    public IframeCategoria() {
        initComponents();
              //Eliminamos el border del JInternalFrame para que no nos muestre las opciones de arriba
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI(); 
        bi.setNorthPane(null);
        
        modeloTabla();
        categoria.obtenerDatos(tblCategorias, modeloCategoria, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        spneProveedores = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        panelIngresarDatos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spneExplicacion = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        panelBotones = new javax.swing.JPanel();
        btnNuevo1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setName("Categoria"); // NOI18N

        panelPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelBuscar.setBackground(new java.awt.Color(246, 246, 246));
        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Realizar busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        panelBuscar.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/buscar26.png"))); // NOI18N
        jLabel7.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 7, 16, 0);
        panelBuscar.add(jLabel7, gridBagConstraints);

        txtBuscar.setBackground(new java.awt.Color(252, 252, 252));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 687;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(19, 5, 16, 15);
        panelBuscar.add(txtBuscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 67, 3, 49);
        panelPrincipal.add(panelBuscar, gridBagConstraints);

        spneProveedores.setPreferredSize(new java.awt.Dimension(452, 390));

        tblCategorias.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spneProveedores.setViewportView(tblCategorias);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 67, 3, 49);
        panelPrincipal.add(spneProveedores, gridBagConstraints);

        panelIngresarDatos.setBackground(new java.awt.Color(246, 246, 246));
        panelIngresarDatos.setPreferredSize(new java.awt.Dimension(368, 170));
        panelIngresarDatos.setRequestFocusEnabled(false);
        panelIngresarDatos.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelIngresarDatos.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel10, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 0);
        panelIngresarDatos.add(txtNombre, gridBagConstraints);

        spneExplicacion.setBorder(null);
        spneExplicacion.setPreferredSize(new java.awt.Dimension(112, 300));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea2.setColumns(9);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(2);
        jTextArea2.setTabSize(5);
        jTextArea2.setText("Una categoria es útil para agrupar los productos permitiendo ofrecer al usuario información más organizada y facilitar su busqueda.");
        spneExplicacion.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(36, 21, 28, 16);
        panelIngresarDatos.add(spneExplicacion, gridBagConstraints);

        jLabel11.setBackground(new java.awt.Color(151, 196, 242));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/proveedor26.png"))); // NOI18N
        jLabel11.setText("Categorías de productos");
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(55, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelIngresarDatos.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*Obligatorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        panelIngresarDatos.add(jLabel12, gridBagConstraints);

        jScrollPane3.setBorder(null);

        txtDescripcion.setBackground(new java.awt.Color(252, 252, 252));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(3);
        txtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jScrollPane3.setViewportView(txtDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 0);
        panelIngresarDatos.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 67, 3, 49);
        panelPrincipal.add(panelIngresarDatos, gridBagConstraints);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(250, 250, 250));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        panelBotones.setPreferredSize(new java.awt.Dimension(120, 23));
        panelBotones.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        btnNuevo1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregarDatos40.png"))); // NOI18N
        btnNuevo1.setText("Nueva categoria");
        btnNuevo1.setToolTipText("Agregar nuevo empleado");
        btnNuevo1.setBorder(null);
        btnNuevo1.setContentAreaFilled(false);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.setFocusPainted(false);
        btnNuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo1.setPreferredSize(new java.awt.Dimension(70, 75));
        btnNuevo1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregarDatos44.png"))); // NOI18N
        btnNuevo1.setRequestFocusEnabled(false);
        btnNuevo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        panelBotones.add(btnNuevo1);

        btnGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar40.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar empleado");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar44.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar40.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita un empleado");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar44.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEditar);

        btnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/delete40.png"))); // NOI18N
        btnRetornar.setText("Eliminar");
        btnRetornar.setToolTipText("Sale de la pestaña");
        btnRetornar.setBorderPainted(false);
        btnRetornar.setContentAreaFilled(false);
        btnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetornar.setFocusPainted(false);
        btnRetornar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetornar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnRetornar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/delete44.png"))); // NOI18N
        btnRetornar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        panelBotones.add(btnRetornar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        categoria.obtenerDatos(tblCategorias, modeloCategoria, txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        if(!utilidades.isChanged())
        {
            tipoOperacion=Utilidades.NUEVO;
            resetFields();
        }
        else
        {
            int opcion=JOptionPane.showConfirmDialog(null,"Esta procesando datos y realizado camios.\n"
                + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(opcion==JOptionPane.YES_OPTION)
            {
                //Si se guardan los datos se reseatean todos los
                if(guardarDatos())
                {
                    tipoOperacion=Utilidades.NUEVO;
                    resetFields();
                    categoria.obtenerDatos(tblCategorias, modeloCategoria, "");
                }

            }
            else if(opcion==JOptionPane.NO_OPTION)
            {
                //Reseteamos la operacion a default
                resetFields();
            }
        }
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if(guardarDatos())
        {
            resetFields();
            categoria.obtenerDatos(tblCategorias, modeloCategoria, "");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //verificamos que no se este realizando otra operacion
        if(tipoOperacion==Utilidades.NUEVO||tipoOperacion==Utilidades.EDITAR)
        {
            //Validamos que se seleccione un campo
            if(tblCategorias.getSelectedRow()>=0)
            {
                if(!utilidades.isChanged())
                {
                    tipoOperacion=Utilidades.EDITAR;
                    categoria.setIdCategoria((Integer)tblCategorias.getValueAt(tblCategorias.getSelectedRow(), 0));
                    txtNombre.setText(tblCategorias.getValueAt(tblCategorias.getSelectedRow(), 1).toString());
                    txtDescripcion.setText(tblCategorias.getValueAt(tblCategorias.getSelectedRow(), 2).toString());
                }
                else
                {
                    int opcion=JOptionPane.showConfirmDialog(null,"Esta procesando datos y realizado camios.\n"
                        + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(opcion==JOptionPane.YES_OPTION)
                    {
                        //Si se guardan los datos se reseatean todos los
                        if(guardarDatos())
                        {
                            //reseteamso los valores a por defecto
                            resetFields();
                            //volvemos a llenar los datos de la tabla
                            categoria.obtenerDatos(tblCategorias, modeloCategoria, "");
                        }

                    }
                    else if(opcion==JOptionPane.NO_OPTION)
                    {
                        //Reseteamos la operacion a default
                        resetFields();
                    }
                }
            }
            else
            JOptionPane.showMessageDialog(this, "Debe seleccionar una categoría para editar");

        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        if(tblCategorias.getSelectedRow()>=0)
        {
            int respuesta=categoria.eliminar((Integer)tblCategorias.getValueAt(tblCategorias.getSelectedRow(),0));

            if(respuesta==Utilidades.REALIZADO)
            {
                JOptionPane.showMessageDialog(null,"Proveedor eliminado con éxito");
                categoria.obtenerDatos(tblCategorias, modeloCategoria, "");
                resetFields();
            }
            else if(respuesta==Utilidades.TIENE_RELACION)
            JOptionPane.showMessageDialog(null,"El proveeodor no se puede elimar porque tiene\n una relación en la tabla productos");

        }
        else
        JOptionPane.showMessageDialog(null, "Debe seleccionar de la tabla al proveedor que desea borrar");

    }//GEN-LAST:event_btnRetornarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtNombreKeyReleased

    //Este metodo es para darle diseño al modelo de la tabla 
   private  void modeloTabla(){
      //Creamos un arreglo de Strings para los encabezados de nuestra tabla
    String encabezados[]= {"ID", "Nombre categoría", "Descripcion"};
    //Creamos un modelo para nuestros arreglo para los encabezados
   modeloCategoria=new DefaultTableModel(null,encabezados){
       /*Creamos un arreglo de tipos para nuestra tabla, dicho arreglo es paralelo con el nombre 
        arreglo de nombres del encabezado*/
        Class tipos[]={
                Integer.class,
                String.class, 
                String.class};
        //Sobre escribimos el metodo getColumIndex para que devuelva la posicion de nuestro arreglo de tipos
        @Override
         public Class getColumnClass(int index){
            return tipos[index];
         }
         //Tambien sobre escribimos el metodo que permite editar las celdas de la tabla
        @Override
         public boolean isCellEditable(int rowIndex,int columnIndex){
             return false;
         }
       };
    //Agregamos nuestro modelo a la tabla
     tblCategorias.setModel(modeloCategoria);
     
   
           
      //Creamos un arreglo con las medidas fijos predeterminados de la tabla para cada celda
      int ancho[]={100,150,700};
      for(int i=0;i<tblCategorias.getColumnCount();i++)
      {
          tblCategorias.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
          tblCategorias.getColumnModel().getColumn(i).setResizable(false);
      }
     utilidades.setTableHeader(tblCategorias);
     tblCategorias.setRowHeight(20);
     }
 //Este metodo se encarga de deicidir que tipo de operacion se realizara. Si es Guardar o Actualizar
   private boolean realizarOperacion(int tipo){
       boolean realizado=false;
       switch(tipo)
       {
            case Utilidades.NUEVO:
                //llenamos la variables de la clase empleados con los valores del campo de texto
                //que luego seran enviadas en el metodo guardar o actualizar
                setDatos();
                //Luego utilizamos las variables para mandar a llamar al metodo guardar
                if(categoria.guardar())
                  realizado=true;  
            break;
            case Utilidades.EDITAR:
                setDatos();
                if(categoria.actualizar())
                    realizado=true;
            break;
       }
       return realizado;
   }
   //Con este metodo asignamos valores a las variables de la clase Proveedor
   private void setDatos(){
       categoria.setNombre(txtNombre.getText());
       categoria.setDescripcion(txtDescripcion.getText());
   }
   
   //Con este metodo guardamos los datos y los actualizamos
   private boolean guardarDatos(){
       boolean realizado=false;
       if(!txtNombre.getText().isEmpty()){
           realizado=realizarOperacion(tipoOperacion);
       }
       else
           JOptionPane.showMessageDialog(null,"El campo de \"Nombre\" no puede ser vacio.");
       
       return realizado;
   }
   //Este metodo reseta todos los campos
   private void resetFields(){
    tblCategorias.clearSelection();
    tipoOperacion=Utilidades.NUEVO;
    utilidades.setChanged(false);
    txtNombre.setText("");
    txtDescripcion.setText("");
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelIngresarDatos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane spneExplicacion;
    private javax.swing.JScrollPane spneProveedores;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
