/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmsoft.Formularios;

import dmsoft.Clases.Entidades.Empleados;
import dmsoft.Clases.Entidades.Roles;
import dmsoft.Clases.Entidades.Utilidades;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany_Hernandez
 */
public class IframeEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeEmpleados
     * @param dimension
     */
    //Creamos objetos para los modelos de nuestra tablas
    DefaultTableModel modeloPrivilegios;
    DefaultTableModel modeloRoles;
    //Creamos un objeto de la clase Usuarios para usarlo
    Roles usuario=new Roles();

    Utilidades utilidades=new Utilidades();
    private int tipoOperacion=Utilidades.DEFAULT;
    Empleados empleado=new Empleados();
    
    //Creamos un formato para la fecha en sql
    SimpleDateFormat formatoFecha=new SimpleDateFormat("yyyy-MM-dd");
    
    public IframeEmpleados() {
        initComponents();
        
      //Eliminamos el border del JInternalFrame para que no nos muestre las opciones de arriba
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI(); 
        bi.setNorthPane(null);

        

        modeloTabla();

        //Una ves que hemos creado el modelo aho le damos formato a la table
        formatoTabla();
                   
        //llamamos este metodo para que nos muestre el panel de empleados
        utilidades.cambiarComponente(tpneEmpleados, panelEmpleados, "Empleados");
        //Cambiamos el header de la tabla
        empleado.obtenerDatos(tblEmpleados, modeloRoles, "Todos", "");
       //Llenamos el JComboBox con el metodo obtenerTipoUsuarios
        empleado.obtenerTiposUsuarios(cbxTipoUsuario);
        
        //Reseteamos la varibale change ya que en el metodo obtenerTipoUsuarios se vuelve positiva
         utilidades.setChanged(false);
         btnRetornar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tpneEmpleados = new javax.swing.JTabbedPane();
        panelEmpleados = new javax.swing.JPanel();
        spneTablaEmpleados = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        panelBuscarEmpleado = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtBuscarEmpleado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cboFiltroEmpleados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelDatos = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        dcrFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spneTxtDescripcion = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextArea();
        txtUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtaInstrucciones = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setBorder(null);
        setName("Empleados"); // NOI18N

        tpneEmpleados.setBackground(new java.awt.Color(252, 252, 252));
        tpneEmpleados.setForeground(new java.awt.Color(51, 51, 51));
        tpneEmpleados.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tpneEmpleados.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tpneEmpleados.setOpaque(true);
        tpneEmpleados.setPreferredSize(new java.awt.Dimension(750, 340));

        panelEmpleados.setLayout(new java.awt.BorderLayout(0, 5));

        tblEmpleados.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tblEmpleados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblEmpleados.setOpaque(false);
        tblEmpleados.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tblEmpleados.setSelectionForeground(new java.awt.Color(226, 226, 226));
        spneTablaEmpleados.setViewportView(tblEmpleados);

        panelEmpleados.add(spneTablaEmpleados, java.awt.BorderLayout.CENTER);

        panelBuscarEmpleado.setBackground(new java.awt.Color(246, 246, 246));
        panelBuscarEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 216, 216)));
        panelBuscarEmpleado.setPreferredSize(new java.awt.Dimension(100, 90));
        panelBuscarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(61, 61, 61));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Buscar");
        panelBuscarEmpleado.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 27));

        txtBuscarEmpleado.setBackground(new java.awt.Color(252, 252, 252));
        txtBuscarEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtBuscarEmpleado.setForeground(new java.awt.Color(30, 30, 30));
        txtBuscarEmpleado.setToolTipText("");
        txtBuscarEmpleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtBuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEmpleadoKeyReleased(evt);
            }
        });
        panelBuscarEmpleado.add(txtBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 450, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(61, 61, 61));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Mostrar");
        panelBuscarEmpleado.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 410, 27));

        cboFiltroEmpleados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        cboFiltroEmpleados.setForeground(new java.awt.Color(30, 30, 30));
        cboFiltroEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Solo los empleados activos", "Solo los empleados inactivos" }));
        cboFiltroEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltroEmpleadosActionPerformed(evt);
            }
        });
        panelBuscarEmpleado.add(cboFiltroEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 300, 30));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Puede realizar una busqueda por los campos de DNI, nombre, apellido,    fecha de nacimiento,   teléfono,  \n correo o usuario.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        panelBuscarEmpleado.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 15, 330, 60));

        panelEmpleados.add(panelBuscarEmpleado, java.awt.BorderLayout.NORTH);

        tpneEmpleados.addTab("Empleados", panelEmpleados);

        panelDatos.setBackground(new java.awt.Color(250, 250, 250));
        panelDatos.setPreferredSize(new java.awt.Dimension(600, 400));
        panelDatos.setLayout(new java.awt.GridBagLayout());

        pnlDatos.setBackground(new java.awt.Color(246, 246, 246));
        pnlDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        pnlDatos.setForeground(new java.awt.Color(204, 204, 204));
        pnlDatos.setPreferredSize(new java.awt.Dimension(702, 140));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 61, 61));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 10, 36);
        pnlDatos.add(jLabel1, gridBagConstraints);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(252, 252, 252));
        txtCodigo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(30, 30, 30));
        txtCodigo.setText("Autogenerado");
        txtCodigo.setAutoscrolls(false);
        txtCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 10, 69);
        pnlDatos.add(txtCodigo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 61, 61));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Número de cedula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel2, gridBagConstraints);

        txtCedula.setBackground(new java.awt.Color(252, 252, 252));
        txtCedula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(30, 30, 30));
        txtCedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDatos.add(txtCedula, gridBagConstraints);

        txtSegundoNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtSegundoNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtSegundoNombre.setForeground(new java.awt.Color(30, 30, 30));
        txtSegundoNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 219, 219), 2, true));
        txtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSegundoNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 34);
        pnlDatos.add(txtSegundoNombre, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(61, 61, 61));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Primer Nombre ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 61, 61));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Segundo Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel4, gridBagConstraints);

        txtPrimerNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtPrimerNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtPrimerNombre.setForeground(new java.awt.Color(30, 30, 30));
        txtPrimerNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrimerNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDatos.add(txtPrimerNombre, gridBagConstraints);

        txtApellidoPaterno.setBackground(new java.awt.Color(252, 252, 252));
        txtApellidoPaterno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtApellidoPaterno.setForeground(new java.awt.Color(30, 30, 30));
        txtApellidoPaterno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDatos.add(txtApellidoPaterno, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(61, 61, 61));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellido paterno ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 61, 61));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha de nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel6, gridBagConstraints);

        txtApellidoMaterno.setBackground(new java.awt.Color(252, 252, 252));
        txtApellidoMaterno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtApellidoMaterno.setForeground(new java.awt.Color(30, 30, 30));
        txtApellidoMaterno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 34);
        pnlDatos.add(txtApellidoMaterno, gridBagConstraints);

        dcrFechaNacimiento.setBackground(new java.awt.Color(237, 237, 255));
        dcrFechaNacimiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        dcrFechaNacimiento.setForeground(new java.awt.Color(30, 30, 30));
        dcrFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 34);
        pnlDatos.add(dcrFechaNacimiento, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(61, 61, 61));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Apellido materno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel7, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(61, 61, 61));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 36);
        pnlDatos.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(61, 61, 61));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(61, 61, 61));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Correo electronico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel12, gridBagConstraints);

        txtTelefono.setBackground(new java.awt.Color(252, 252, 252));
        txtTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(30, 30, 30));
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDatos.add(txtTelefono, gridBagConstraints);

        txtCorreo.setBackground(new java.awt.Color(252, 252, 252));
        txtCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(30, 30, 30));
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 34);
        pnlDatos.add(txtCorreo, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("*");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setPreferredSize(new java.awt.Dimension(8, 8));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlDatos.add(jLabel14, gridBagConstraints);

        jLabel18.setBackground(new java.awt.Color(151, 196, 242));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/usuario26.png"))); // NOI18N
        jLabel18.setText("Datos generales");
        jLabel18.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 44;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        pnlDatos.add(jLabel18, gridBagConstraints);

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("*");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlDatos.add(jLabel15, gridBagConstraints);

        spneTxtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        txtdireccion.setBackground(new java.awt.Color(252, 252, 252));
        txtdireccion.setColumns(20);
        txtdireccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(30, 30, 30));
        txtdireccion.setLineWrap(true);
        txtdireccion.setRows(2);
        txtdireccion.setToolTipText("");
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
        });
        spneTxtDescripcion.setViewportView(txtdireccion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 37);
        pnlDatos.add(spneTxtDescripcion, gridBagConstraints);

        txtUsuario.setBackground(new java.awt.Color(252, 252, 252));
        txtUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 10, 0);
        pnlDatos.add(txtUsuario, gridBagConstraints);
        txtUsuario.setText(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(61, 61, 61));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Usuario");
        jLabel9.setPreferredSize(new java.awt.Dimension(30, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 10, 36);
        pnlDatos.add(jLabel9, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(61, 61, 61));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/contraseña20.png"))); // NOI18N
        jLabel8.setText("Contraseña");
        jLabel8.setPreferredSize(new java.awt.Dimension(30, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel8, gridBagConstraints);

        txtPassword.setBackground(new java.awt.Color(252, 252, 252));
        txtPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDatos.add(txtPassword, gridBagConstraints);

        cbxTipoUsuario.setBackground(new java.awt.Color(237, 237, 255));
        cbxTipoUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxTipoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        cbxTipoUsuario.setToolTipText("");
        cbxTipoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoUsuarioItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlDatos.add(cbxTipoUsuario, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(61, 61, 61));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Tipo de usuario");
        jLabel13.setPreferredSize(new java.awt.Dimension(30, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 10, 36);
        pnlDatos.add(jLabel13, gridBagConstraints);

        jLabel21.setBackground(new java.awt.Color(151, 196, 242));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/estado26.png"))); // NOI18N
        jLabel21.setText("Estado");
        jLabel21.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        pnlDatos.add(jLabel21, gridBagConstraints);

        jLabel20.setBackground(new java.awt.Color(151, 196, 242));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/seguridad26.png"))); // NOI18N
        jLabel20.setText("Acceso");
        jLabel20.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        pnlDatos.add(jLabel20, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 44;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
        pnlDatos.add(jSeparator1, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        pnlDatos.add(jSeparator2, gridBagConstraints);

        cbxEstado.setBackground(new java.awt.Color(204, 204, 255));
        cbxEstado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxEstado.setForeground(new java.awt.Color(51, 51, 51));
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEstadoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 10, 34);
        pnlDatos.add(cbxEstado, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(61, 61, 61));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 10, 36);
        pnlDatos.add(jLabel23, gridBagConstraints);

        txtaInstrucciones.setEditable(false);
        txtaInstrucciones.setBackground(new java.awt.Color(246, 246, 246));
        txtaInstrucciones.setColumns(23);
        txtaInstrucciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtaInstrucciones.setForeground(new java.awt.Color(137, 137, 135));
        txtaInstrucciones.setLineWrap(true);
        txtaInstrucciones.setRows(3);
        txtaInstrucciones.setTabSize(10);
        txtaInstrucciones.setText("El estado del empleado debe ser activo si  esta laborando en la empresa, de lo contrario debe ser inactivo.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 10, 0);
        pnlDatos.add(txtaInstrucciones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.gridheight = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 202;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 46, 15, 32);
        panelDatos.add(pnlDatos, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*  Campos obligatarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 60, 13, 0);
        panelDatos.add(jLabel19, gridBagConstraints);

        tpneEmpleados.addTab("Agregar / Actuilzar empleado", panelDatos);

        getContentPane().add(tpneEmpleados, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(250, 250, 250));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        panelBotones.setPreferredSize(new java.awt.Dimension(120, 23));
        panelBotones.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        btnNuevo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregar40.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Agregar nuevo empleado");
        btnNuevo.setBorder(null);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFocusPainted(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setPreferredSize(new java.awt.Dimension(70, 75));
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregar44.png"))); // NOI18N
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelBotones.add(btnNuevo);

        btnGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar40.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar empleado");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar44.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar40.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita un empleado");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar44.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEditar);

        btnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/return40.png"))); // NOI18N
        btnRetornar.setText("Regresar");
        btnRetornar.setToolTipText("Sale de la pestaña");
        btnRetornar.setBorderPainted(false);
        btnRetornar.setContentAreaFilled(false);
        btnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetornar.setFocusPainted(false);
        btnRetornar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetornar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnRetornar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/return44.png"))); // NOI18N
        btnRetornar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        panelBotones.add(btnRetornar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboFiltroEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltroEmpleadosActionPerformed

     empleado.obtenerDatos(tblEmpleados, modeloRoles, getFiltro(cboFiltroEmpleados.getSelectedIndex()), txtBuscarEmpleado.getText());
        
    }//GEN-LAST:event_cboFiltroEmpleadosActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      //Validamos que no se este realizando ninguna otra operacion y que la operacion sea por DEFAULT
       if(tipoOperacion==Utilidades.DEFAULT)
       {
          //Validamos que se haya seleccionado un empleado de la tabla
           if(tblEmpleados.getSelectedRow()>=0)
           {
               //Cambiamos el tipo de operacion
               tipoOperacion=Utilidades.EDITAR;
                btnRetornar.setVisible(true);
                
               //Consultamos todos los datos del empleado a la base de datos por medio de su cedula
               //Este metodo llenara las variables de la clase empleados
               empleado.obtenerDatos(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(),0).toString());
                
               //Accedemos a las variables por medio de los metodos get y las asignamos a los campos
                getDatos();   
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Seleccione un empleado de la tabla");
           }
       }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
       int opcion;
        if(utilidades.isChanged())
        {
              opcion=JOptionPane.showConfirmDialog(null,"Los datos se modificaron.\n"
                                           + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
              if(opcion==JOptionPane.YES_OPTION)
              {
                  if(guardarDatos())
                  {
                      btnRetornar.setVisible(false);
                      resetFields();
                      utilidades.cambiarComponente(tpneEmpleados, panelEmpleados, "Empleados");
                  }
              }
              else if(opcion==JOptionPane.NO_OPTION)
              {
                  //Reseteamos la operacion a default
                  btnRetornar.setVisible(false);
                  resetFields();
                  utilidades.cambiarComponente(tpneEmpleados, panelEmpleados, "Empleados");
                  
              }
                  
        }
        else
        {
            //Reseteamos la operacion a default
                 btnRetornar.setVisible(false);
                  resetFields();
                 utilidades.cambiarComponente(tpneEmpleados, panelEmpleados, "Empleados");
        }
           
            
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtPrimerNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerNombreKeyReleased
      utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtPrimerNombreKeyReleased

    private void txtApellidoPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtApellidoPaternoKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void txtSegundoNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoNombreKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtSegundoNombreKeyReleased

    private void txtApellidoMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyReleased
      utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtApellidoMaternoKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
      utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
       utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void cbxTipoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoUsuarioItemStateChanged
     utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxTipoUsuarioItemStateChanged

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

   if(!utilidades.isChanged())
    {
         tipoOperacion=Utilidades.NUEVO;
         btnRetornar.setVisible(true);
         utilidades.cambiarComponente(tpneEmpleados, panelDatos, "Agregar nuevo empleado");
    }
    else
    {
        int opcion=JOptionPane.showConfirmDialog(null,"Los datos se modificaron.\n"
                                           + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opcion==JOptionPane.YES_OPTION)
         {
                if(guardarDatos())
                {
                  resetFields();
                  utilidades.cambiarComponente(tpneEmpleados, panelDatos, "Agregar nuevo empleado");
                }
                  
              }
              else if(opcion==JOptionPane.NO_OPTION)
              {
                  //Reseteamos la operacion a default
                  resetFields();
                  utilidades.cambiarComponente(tpneEmpleados, panelDatos, "Agregar nuevo empleado");
              }
    }
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(tipoOperacion==Utilidades.NUEVO||tipoOperacion==Utilidades.EDITAR)
        {
             if(guardarDatos())
             {
                utilidades.cambiarComponente(tpneEmpleados, panelEmpleados, "Empleados");
                btnRetornar.setVisible(false);
             }
             
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEstadoItemStateChanged
           utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxEstadoItemStateChanged

    private void txtBuscarEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEmpleadoKeyReleased
      empleado.obtenerDatos(tblEmpleados, modeloRoles, getFiltro(cboFiltroEmpleados.getSelectedIndex()), txtBuscarEmpleado.getText());
        
    }//GEN-LAST:event_txtBuscarEmpleadoKeyReleased
     
    //Este metodo es para darle diseño al modelo de la tabla 
   private  void modeloTabla(){
      //Creamos un arreglo de Strings para los encabezados de nuestra tabla
    String encabezados[]= {"DNI", "Nombre", "Apellidos", "Fecha nacimiento", 
                           "Direccion", "Telefono", "Correo",
                            "Usuario", "Clave", "Estado"};
    //Creamos un modelo para nuestros arreglo para los encabezados
   modeloRoles=new DefaultTableModel(null,encabezados){
       /*Creamos un arreglo de tipos para nuestra tabla, dicho arreglo es paralelo con el nombre 
        arreglo de nombres del encabezado*/
        Class tipos[]={
                String.class,
                String.class, 
                String.class,
                Date.class,
                String.class,
                String.class,
                String.class,
                String.class,
                String.class,
                String.class};
        //Sobre escribimos el metodo getColumIndex para que devuelva la posicion de nuestro arreglo de tipos
        @Override
         public Class getColumnClass(int index){
            return tipos[index];
         }
         //Tambien sobre escribimos el metodo que permite editar las celdas de la tabla
        @Override
         public boolean isCellEditable(int rowIndex,int columnIndex){
             return false;
         }
       };
    //Agregamos nuestro modelo a la tabla
      tblEmpleados.setModel(modeloRoles);
     }
    
    
    //Este metodo se encarga del diseño de la tabla, es decir del formato de las celdas
    private void formatoTabla()
    {
       int dni=180,
           Nombre=150,
           apellido=150,
           fechaNacimiento=120,
           direccion=200,
           telefono=120,
           correo=170,
           user=120,
           clave=120,
           estado=130;
           
      //Creamos un arreglo con las medidas fijos predeterminados de la tabla para cada celda
      int ancho[]={dni,Nombre,apellido,fechaNacimiento,direccion,telefono,correo,user,clave,estado};
      for(int i=0;i<tblEmpleados.getColumnCount();i++)
      {
          tblEmpleados.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
          tblEmpleados.getColumnModel().getColumn(i).setResizable(false);
      }
      tblEmpleados.setRowHeight(20);
      //Establecemos el header
      new Utilidades().setTableHeader(tblEmpleados);
    }
   

    //Este metodo se encarga de deicidir que tipo de operacion se realizara. Si es Guardar o Actualizar
   private boolean realizarOperacion(int tipo){
       boolean realizado=false;
       switch(tipo)
       {
            case Utilidades.NUEVO:
                //llenamos la variables de la clase empleados con los valores del campo de texto
                //que luego seran enviadas en el metodo guardar o actualizar
                setDatos(tipo);
                //Luego utilizamos las variables para mandar a llamar al metodo guardar
                if(empleado.guardar())
                  realizado=true;  
            break;
            case Utilidades.EDITAR:
                setDatos(tipo);
                if(empleado.actualizar())
                    realizado=true;
            break;
       }
       return realizado;
   }

   //Con este metodo obtenemos todos los valores de los campos
   private void setDatos(int vericacion)
   {
       //Especificamos que solo cuando se valla a editar guardara el valor del id del empleado
       if(vericacion==Utilidades.EDITAR)
        empleado.setIdEmpleado(Integer.parseInt(txtCodigo.getText()));
           
      empleado.setDni(txtCedula.getText());
      empleado.setpNombre(txtPrimerNombre.getText());
      empleado.setsNombre(txtSegundoNombre.getText());
      empleado.setApellidoPaterno(txtApellidoPaterno.getText());
      empleado.setApellidoMaterno(txtApellidoMaterno.getText());
      empleado.setTelefono(txtTelefono.getText());
      empleado.setDireccion(txtdireccion.getText());
      //validamos que la fecha no sea nulla 
      if(dcrFechaNacimiento.getDate()!=null)
      {
        empleado.setFechaNacimiento(Date.valueOf(formatoFecha.format(dcrFechaNacimiento.getDate())));
      }
      else
      {
          empleado.setFechaNacimiento(null);  
      }
         
      empleado.setCorreo(txtCorreo.getText());
     //Validamos que el usuario tengo usuario, de lo contrario se asigna null, para evitar conflicto en la BD
      if(txtUsuario.getText().isEmpty())
          empleado.setUsuario(null);
      else
          empleado.setUsuario(txtUsuario.getText());
      empleado.setClave(txtPassword.getText());
      empleado.setTipoUsuario((String)cbxTipoUsuario.getSelectedItem());
      empleado.setEstado((String)cbxEstado.getSelectedItem());
   }
   
   //Con este metodo asignamos los valores a las variables a los campos 
   private void  getDatos()
   {
      
       utilidades.cambiarComponente(tpneEmpleados, panelDatos, "Editar datos del empleado");
       txtCodigo.setText(String.valueOf(empleado.getIdEmpleado()));
       txtCedula.setText(empleado.getDni());
       txtPrimerNombre.setText(empleado.getpNombre());
       txtSegundoNombre.setText(empleado.getsNombre());
       txtApellidoPaterno.setText(empleado.getApallidoPaterno());
       txtApellidoMaterno.setText(empleado.getApellidoMaterno());
       txtTelefono.setText(empleado.getTelefono());
       txtdireccion.setText(empleado.getDireccion());
       dcrFechaNacimiento.setDate(empleado.getFechaNacimiento());
       txtCorreo.setText(empleado.getCorreo());
       txtUsuario.setText(empleado.getUsuario());
       txtPassword.setText(empleado.getClave());
       cbxEstado.setSelectedItem(empleado.getEstado());
       cbxTipoUsuario.setSelectedItem(empleado.getTipoUsuario());
       /*Debido a que los combobox tiene implementa el ItemListener cada vez que seleccionamos, un item
        el envento detecta el cambio y marca la varible change como true, entonces cada vez que se hace 
       una seleccion en los comboBox entonces la reseteamos porque no es un cambio que nosotros hacemos*/
       utilidades.setChanged(false);
   }
   
   //Con este metodo vamos a limpiar los campos
   private void resetFields()
   {
       tipoOperacion=Utilidades.DEFAULT;
       txtCodigo.setText("Autogeneredado");
       txtCedula.setText("");
       txtPrimerNombre.setText("");
       txtSegundoNombre.setText("");
       txtApellidoPaterno.setText("");
       txtApellidoMaterno.setText("");
       txtTelefono.setText("");
       txtdireccion.setText("");
       dcrFechaNacimiento.setDate(null);
       txtCorreo.setText("");
       txtUsuario.setText("");
       txtPassword.setText("");
       cbxEstado.setSelectedIndex(0);
       cbxTipoUsuario.setSelectedIndex(0);
       txtBuscarEmpleado.setText("");
       cboFiltroEmpleados.setSelectedIndex(0);
       /*Debido a que los combobox tiene implementa el ItemListener cada vez que seleccionamos, un item
        el envento detecta el cambio y marca la varible change como true, entonces cada vez que se hace 
       una seleccion en los comboBox entonces la reseteamos porque no es un cambio que nosotros hacemos*/
       utilidades.setChanged(false);
     
   }
   
   private boolean guardarDatos(){
       boolean realizado=false;
       //Validamos los campos obligatorios
        if(!utilidades.validarCampos(txtCedula.getText(),txtPrimerNombre.getText(),txtApellidoPaterno.getText()))
            {
                //LLamamos la funcion realizarOperacion para que defina si esta guardando o actualizando
               if(realizarOperacion(tipoOperacion))
               {
                  resetFields();
                  empleado.obtenerDatos(tblEmpleados, modeloRoles, "Todos", "");
                  realizado=true;
               }
                  
            }
            else
              JOptionPane.showMessageDialog(null,"Campos obligatorios vacios");
        return realizado;
   }
   
   private String getFiltro(int index)
   {
       String filtro="";
        switch (index) {
            case 0:
                filtro="Todos";
                break;
            case 1:
                filtro="Activo";
                break;
            case 2:
                filtro="Inactivo";
                break;
            default:
                break;
        }
       return filtro;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> cboFiltroEmpleados;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private com.toedter.calendar.JDateChooser dcrFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscarEmpleado;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JScrollPane spneTablaEmpleados;
    private javax.swing.JScrollPane spneTxtDescripcion;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTabbedPane tpneEmpleados;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBuscarEmpleado;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextArea txtaInstrucciones;
    private javax.swing.JTextArea txtdireccion;
    // End of variables declaration//GEN-END:variables
}
