/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmsoft.Formularios;

import dmsoft.Clases.Entidades.Empresa;
import dmsoft.Clases.Entidades.Utilidades;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Dany_Hernandez
 */
public class IframeEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeEmpresa
     * @param dimension
     */
    //Creamos un objeto de la clase empresa
    Empresa empresa= new Empresa();
    int tipoOperacion=0;
    boolean realizoCambios=false,eliminoLogo=false;
    String auxRutaLogo="";
    String rutaLogoRelativa="";
    /*Esta varible contendra el directorio del usario mas la carpeta src que pertenece a 
    al proyecto que utilizara para complementar la ruta del archivo*/
    String dirUsuario=System.getProperty("user.dir")+"\\src";
    /*Este objeto de tipo File contendra el archivo del  logo, en esta caso se 
    se usa global porque sirve para previsualizar el logo aunque no se cambie*/
    File archivoLogo=null;
    Utilidades utilidades=new Utilidades();
    public IframeEmpresa() {
        initComponents();
        //Eliminamos el border del JInternalFrame para que no nos muestre las opciones de arriba
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI(); 
        bi.setNorthPane(null);
      //  setSize(dimension);
        //LLenamos los todos los campos y comprobamos que la empresa no este agregada
        llenarCampos();
        existeEmpresaRegistrada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCodigoEmpresa = new javax.swing.JTextField();
        txtRtn = new javax.swing.JTextField();
        txtRubro = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        speDireccion = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        pnlLogo = new javax.swing.JPanel();
        btnSubirLogo = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnEliminarLogo = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        txtCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSlogan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAviso = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBorder(null);
        setName("Empresa"); // NOI18N

        pnlPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(808, 420));
        pnlPrincipal.setLayout(new java.awt.GridBagLayout());

        pnlDatos.setBackground(new java.awt.Color(246, 246, 246));
        pnlDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel3, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Direccion");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Rubro");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("RTN");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel8, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Slogan");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Código de empresa");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel12, gridBagConstraints);

        txtCodigoEmpresa.setBackground(new java.awt.Color(252, 252, 252));
        txtCodigoEmpresa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtCodigoEmpresa.setForeground(new java.awt.Color(40, 55, 71));
        txtCodigoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCodigoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEmpresaActionPerformed(evt);
            }
        });
        txtCodigoEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtCodigoEmpresa, gridBagConstraints);

        txtRtn.setBackground(new java.awt.Color(252, 252, 252));
        txtRtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtRtn.setForeground(new java.awt.Color(40, 55, 71));
        txtRtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtRtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRtnKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtRtn, gridBagConstraints);

        txtRubro.setBackground(new java.awt.Color(252, 252, 252));
        txtRubro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtRubro.setForeground(new java.awt.Color(40, 55, 71));
        txtRubro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtRubro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRubroKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtRubro, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(40, 55, 71));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtNombre, gridBagConstraints);

        speDireccion.setBorder(null);

        txtDireccion.setBackground(new java.awt.Color(252, 252, 252));
        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(40, 55, 71));
        txtDireccion.setLineWrap(true);
        txtDireccion.setRows(2);
        txtDireccion.setTabSize(4);
        txtDireccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtDireccion.setDoubleBuffered(true);
        txtDireccion.setName(""); // NOI18N
        txtDireccion.setSelectionColor(new java.awt.Color(0, 153, 204));
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });
        speDireccion.setViewportView(txtDireccion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 17);
        pnlDatos.add(speDireccion, gridBagConstraints);

        pnlLogo.setBackground(new java.awt.Color(246, 246, 246));
        pnlLogo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Logo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlLogo.setPreferredSize(new java.awt.Dimension(400, 200));
        pnlLogo.setRequestFocusEnabled(false);
        pnlLogo.setLayout(new java.awt.GridBagLayout());

        btnSubirLogo.setBackground(new java.awt.Color(249, 249, 249));
        btnSubirLogo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        btnSubirLogo.setForeground(new java.awt.Color(51, 51, 51));
        btnSubirLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/subirLogo32.png"))); // NOI18N
        btnSubirLogo.setText("Agregar Logo");
        btnSubirLogo.setToolTipText("");
        btnSubirLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 2, true));
        btnSubirLogo.setContentAreaFilled(false);
        btnSubirLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubirLogo.setFocusPainted(false);
        btnSubirLogo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSubirLogo.setOpaque(true);
        btnSubirLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirLogoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlLogo.add(btnSubirLogo, gridBagConstraints);

        lblLogo.setBackground(new java.awt.Color(226, 234, 244));
        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setToolTipText("");
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogo.setOpaque(true);
        lblLogo.setPreferredSize(new java.awt.Dimension(137, 137));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLogoMouseReleased(evt);
            }
        });
        lblLogo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lblLogoComponentResized(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLogo.add(lblLogo, gridBagConstraints);

        btnEliminarLogo.setBackground(new java.awt.Color(249, 249, 249));
        btnEliminarLogo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        btnEliminarLogo.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/removerLogo32.png"))); // NOI18N
        btnEliminarLogo.setText("Eliminar logo");
        btnEliminarLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 2, true));
        btnEliminarLogo.setContentAreaFilled(false);
        btnEliminarLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarLogo.setFocusPainted(false);
        btnEliminarLogo.setOpaque(true);
        btnEliminarLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLogoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlLogo.add(btnEliminarLogo, gridBagConstraints);

        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(3);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setTabSize(2);
        jTextArea1.setText("Se recomienda que que la imagen tenga un dimension de 230 px de ancho por 140px de alto, para mantener la calidad.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 0, 0);
        pnlLogo.add(jTextArea1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 8, 8, 17);
        pnlDatos.add(pnlLogo, gridBagConstraints);

        txtCorreo.setBackground(new java.awt.Color(252, 252, 252));
        txtCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(40, 55, 71));
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtCorreo, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Correo electronico");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel10, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telefono");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 0, 17);
        pnlDatos.add(jLabel5, gridBagConstraints);

        txtTelefono.setBackground(new java.awt.Color(252, 252, 252));
        txtTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(40, 55, 71));
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtTelefono, gridBagConstraints);

        txtFax.setBackground(new java.awt.Color(252, 252, 252));
        txtFax.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        txtFax.setForeground(new java.awt.Color(40, 55, 71));
        txtFax.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 8, 0);
        pnlDatos.add(txtFax, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("FAX");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 15, 8, 17);
        pnlDatos.add(jLabel9, gridBagConstraints);

        txtSlogan.setBackground(new java.awt.Color(252, 252, 252));
        txtSlogan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtSlogan.setForeground(new java.awt.Color(51, 51, 51));
        txtSlogan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtSlogan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSloganKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pnlDatos.add(txtSlogan, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(151, 196, 242));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/empresaLogo26.png"))); // NOI18N
        jLabel1.setText("Datos de la Empresa");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 39;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 2.0;
        pnlDatos.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlDatos.add(jLabel2, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlDatos.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.gridheight = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 75, 0, 29);
        pnlPrincipal.add(pnlDatos, gridBagConstraints);

        lblAviso.setForeground(new java.awt.Color(204, 0, 0));
        lblAviso.setText("* Campos obligarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 75, 60, 0);
        pnlPrincipal.add(lblAviso, gridBagConstraints);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(250, 250, 250));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        panelBotones.setPreferredSize(new java.awt.Dimension(120, 80));
        panelBotones.setLayout(new java.awt.GridLayout(9, 1));

        btnGuardar.setBackground(new java.awt.Color(249, 249, 249));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar40.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(true);
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 75));
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar44.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnCancelar.setBackground(new java.awt.Color(249, 249, 249));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/home40.png"))); // NOI18N
        btnCancelar.setText("Inicio");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setOpaque(true);
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 75));
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/home44.png"))); // NOI18N
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCancelar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpresaActionPerformed

    private void txtCodigoEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaKeyReleased
        if(!realizoCambios)
        realizoCambios=utilidades.onChange(evt);
    }//GEN-LAST:event_txtCodigoEmpresaKeyReleased

    private void txtRtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRtnKeyReleased
        if(!realizoCambios)
        realizoCambios=utilidades.onChange(evt);
    }//GEN-LAST:event_txtRtnKeyReleased

    private void txtRubroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRubroKeyReleased
        if(!realizoCambios)
        realizoCambios=utilidades.onChange(evt);
    }//GEN-LAST:event_txtRubroKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if(!realizoCambios)
        realizoCambios=utilidades.onChange(evt);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        if(!realizoCambios)
        realizoCambios=utilidades.onChange(evt);
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void btnSubirLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirLogoActionPerformed
        seleccionarArchivo();
    }//GEN-LAST:event_btnSubirLogoActionPerformed

    private void lblLogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseReleased
        JOptionPane.showMessageDialog(null, "alto "+lblLogo.getHeight()+" ancho "+lblLogo.getHeight());
    }//GEN-LAST:event_lblLogoMouseReleased

    private void lblLogoComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblLogoComponentResized
        //setLogo(empresa.getRutaLogo());
    }//GEN-LAST:event_lblLogoComponentResized

    private void btnEliminarLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLogoActionPerformed
        if(JOptionPane.showConfirmDialog(null,"¿Seguro que desea eliminar el logo actual?")==JOptionPane.YES_OPTION)
        {
            //Eliminamos el logo
            setLogo("");
            //Cambiamos el estado de la variable eliminoLogo a verdadero
            eliminoLogo=true;
            /*Copiamos la ruta del logo actual y la guardammos en la variable
            auxRutaLogo para eliminarla en caso de que los cambios se guarden*/
            auxRutaLogo=empresa.getRutaLogo();
            btnEliminarLogo.setVisible(false);
            /*Si se selecciono un logo y se borro sin haberlo guardado  en la base de datos
            ese archivo se asigna null ya que no se utilizará porque se borro, sin haberlo guardado*/
            archivoLogo=null;
            btnSubirLogo.setText("Agregar logo");
        }
    }//GEN-LAST:event_btnEliminarLogoActionPerformed

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        if(!realizoCambios)
        realizoCambios=new Utilidades().onChange(evt);
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        if(!realizoCambios)
        realizoCambios=new Utilidades().onChange(evt);
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyReleased
        if(!realizoCambios)
        realizoCambios=new Utilidades().onChange(evt);
    }//GEN-LAST:event_txtFaxKeyReleased

    private void txtSloganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSloganKeyReleased
        if(!realizoCambios)
        realizoCambios=utilidades.onChange(evt);
    }//GEN-LAST:event_txtSloganKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      if(realizoCambios)
           guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed


    //Llenar campos
    private void llenarCampos()
    {
        /*Este metodo asigna los valores de la base de datos a las variables declaradas en la clase Empresa
        y estas una vez  tienen asignado un valor se llaman mediante el metodo get de cada una para extraer 
        su valor*/
        empresa.obtenerDatos();
        //Asignamos datos
        txtCodigoEmpresa.setText(empresa.getCodigo());
        txtRtn.setText(empresa.getRtn());
        txtNombre.setText(empresa.getNombre());
        txtRubro.setText(empresa.getRubro());
        txtDireccion.setText(empresa.getDireccion());
        txtSlogan.setText(empresa.getSlogan());
        txtTelefono.setText(empresa.getTelefono());
        txtCorreo.setText(empresa.getCorreo());
        txtFax.setText(empresa.getFax());
        setLogo(dirUsuario+empresa.getRutaLogo());

}
    
   /*Este metodo permite seleccionar archivos en este caso seleccionara el logo de la empresa*/
    private void seleccionarArchivo()
    {
        
        //Creamos el JFileChooser
        JFileChooser selector=new JFileChooser("Seleccionar Logo");
        //Obtenemos el directorio de inicio del usario y luego agragamos la carpeta Pictures para crear crear nuestro directorio por defecto
       String dirDefault=System.getProperty("user.home")+"\\Pictures";

       //Tenemos creado nuestro auxRutaLogo por default,creamos una archivo con esa auxRutaLogo y la agregamos al JFIleChooser
       File currentFile=new File(dirDefault);
       selector.setCurrentDirectory(currentFile);
       //Creamos un filtro de archivos y lo agregamos
       FileNameExtensionFilter filtro= new FileNameExtensionFilter("jpg & png & jepg","jpg","png","jpeg");
       selector.setFileFilter(filtro);

       int accion=selector.showOpenDialog(null);

       //Si se eligio un archivo entonces realiza lo siguiente
        if(accion==JFileChooser.APPROVE_OPTION)
        {   
              //Cambiamos la etiqueta del boton btnSubirLogo
              btnSubirLogo.setText("Cambiar logo");
              //Al seleccionar un archivo cambiamos a true la variable "onChange" porque se modifico se cambio de archivo
              realizoCambios=true;
              /*Si habia borrado un logo entonces la variable eliminoLogo sera true
              pero si ha seleccionado uno nuevo entonces debe ser falsa porque se agrego
              el nuevo logo sustituye al que se borro (btnEliminarLogo)*/
              eliminoLogo=false;
              //Obtenemos el archivo seleccionado
              archivoLogo=selector.getSelectedFile();
             
              /*Al cambiar el logo la variable auxiliar "auxRutaLogo" guarda la ruta del logo
               actual para borrarlo en caso de actualizar el logo*/
               auxRutaLogo=empresa.getRutaLogo();

                /*Llamamos al metodo setLogo y a su vez pasamos como parametro "ruta absuluta del archivo"
                para visualizar como se veria el logo*/ 
                setLogo(archivoLogo.getAbsolutePath());
                //Tambien habilitamos la opcion de elimar logo ya que hemos agregado uno nuevo
                btnEliminarLogo.setVisible(true);
        }
    }
    
    /*Con este metodo copiamos un archivo a las carpetas de archivo del programa
    y retorna una cadena que contendra la auxRutaLogo relativa del archivo copiado*/
    private String copiarArchivo(File archivoLogo)
    {
        String rutaRelativa="";
         try 
            {  
                //Creamos una variable que almacenara nuestra dirección de destino
                String dest=dirUsuario+"/dmsoft/Imagenes/"+archivoLogo.getName();
               
                /*Luego convertimos "dest" a tipo Path, que esta estandariza la direccion de ubicación
                Por ejemplo dest= C:\Users\Documents/imagenes al convertirla a Path quedaria así
                destino=C:\Users\Documents\imagenes ya que lo que hace es colocar el caracter
                que usa windows para separar componentes de una ruta en este caso \ */
                Path destino=Paths.get(dest);
               
                /*Luego obtenemos la ruta de origen del archivo, en este caso tambien lo convertimos
                a tipo Path*/
                String orig=archivoLogo.getPath();
                Path origen=Paths.get(orig);
                
                /*Ahora copiamos el archivo, estableciendo la ruta de origen y destino
                y la constante REPLACE_EXISTING  establece que si ya hay un archivo con
                igual nombre lo borraigual lo borrara antes de copiarlo*/
                Files.copy(origen,destino,REPLACE_EXISTING);
  
               /*Por ultimo creamos la ruta relativa del archivo para que lo retorne la funcion */
               rutaRelativa="\\dmsoft\\Imagenes\\"+archivoLogo.getName(); 
            }
         
         catch (IOException e)
            {
                JOptionPane.showMessageDialog(this,"Error al copiar archivo \n"+e);
                /*En caso de no poder copiarse el archivo entonces se devolvera la 
                la ruta del logo actual, y este se encuentra almacenado 
                en la variable rutaLogo en la clase Empresa*/ 
            }
         return rutaRelativa;
    }
    
    /*Con este metodo agregamos el logo a nuesto JLabel lblLogo*/
    private void setLogo(String rutaLogo)
    {
       /*Verificamos que sea un archivo el que se encuentra la ruta especifica
       y no un un Directorio(Carpeta)*/
       if(esArchivo(rutaLogo)&& !rutaLogo.equals("") && rutaLogo!=null)
       {
            try
            {
             /*En este caso Creamos una instancia de la Super Clase Image ya que de esta heredan
             todas las clases para el manejo de imagenes y obtenmos la imagen de la ruta que pasamos como parametro*/
             Image logo=getToolkit().getImage(rutaLogo);
             if(lblLogo.getHeight()==0||lblLogo.getWidth()==0)
                 
             logo=logo.getScaledInstance(390,236, Image.SCALE_SMOOTH);
             else
                  logo=logo.getScaledInstance(lblLogo.getWidth(),lblLogo.getHeight(), Image.SCALE_SMOOTH);
             /*Una ves que tenemos nuestra imagen ahora lo vamos a redimencionar a las medidas de nuestro JLabel
             obteniendo su ancho y alto y le establecemos que queremos un escalado con suavidad de imagen*/
            lblLogo.setIcon(new ImageIcon(logo));
            lblLogo.setText("");
            lblLogo.setBackground(Color.WHITE);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error al cargar logo\n"+ e);  
            }      
       }
       else
       {
           lblLogo.setIcon(null);
           lblLogo.setText("Logo aquí");
         //   lblLogo.setBackground(new Color(214, 234, 248 ));
       }
   }    
    
    //Con este metodo comprobamos si existe un archivo 
    private boolean existeArchivo(String rutaArchivo)
    {
         File archivo=new File(rutaArchivo);
         if(archivo.exists())
             return true;
         else 
             return false;
    }
    
    //Con este metodo comprobamos si es archivo o directorio lo que se encuentra en la ruta
     private boolean esArchivo(String rutaArchivo)
    {
         File archivo=new File(rutaArchivo);
         if(archivo.isFile())
             return true;
         else 
             return false;
    }
    /*Con este metodo recogemos los valores de todos los campos y los almacenamos en los 
    las variables de la clase Empresa*/
    private void getValores(){
     empresa.setCodigo(txtCodigoEmpresa.getText());
     empresa.setRtn(txtRtn.getText());
     empresa.setNombre(txtNombre.getText());
     empresa.setRubro(txtRubro.getText());
     empresa.setSlogan(txtSlogan.getText());
     empresa.setCorreo(txtCorreo.getText());
     empresa.setTelefono(txtTelefono.getText());
     empresa.setFax(txtFax.getText());
     empresa.setDireccion(txtDireccion.getText());
     //Se obtienen los valores, entonces copiamos la imagen del logo si "archivoLogo" no esta vacio
    if(archivoLogo!=null)
    {
         rutaLogoRelativa=copiarArchivo(archivoLogo);
          if(!rutaLogoRelativa.equals(""))
          {
              empresa.setRutaLogo(rutaLogoRelativa);
          }
    }
    //Si no comprueba que no se haya elimado el logo
    else if(eliminoLogo)
    {
        /*En caso de haber borrado el logo entonces, pasamos una 
        rut vacia porque el logo se elimino*/
        empresa.setRutaLogo("");
    }
     
    }
    
    //Con este metodo comprobamos si existe una empresa registrada o sino la guarda
  private  void existeEmpresaRegistrada()
  {
     //si existe la empresa entonces la operacion sera 1=Actualizar, de lo contrario 0=guardar
        if(empresa.hayRegistros())
        {
            tipoOperacion=Utilidades.ACTUALIZAR; 
        }
        else
        {
          tipoOperacion=Utilidades.GUARDAR;  
        }
        //Verifica que si hay logo de lo contrario hace invicible el boton EliminarLogo
        //y cambia la etiqueta al boton agregar logo
        if(empresa.getRutaLogo().isEmpty()||empresa.getRutaLogo()==null)
        {
            btnEliminarLogo.setVisible(false);
            btnSubirLogo.setText("Agregar logo");
        }
        else
        {
            btnEliminarLogo.setVisible(true);
            btnSubirLogo.setText("Cambiar logo");
        }
            
    }
    
  
  //Este medoto guarda o actualiza los datos
  private boolean guardar(){
      //esta variable verifica que se hayan guardado los datos 
       boolean realizado=false; 
      if(!txtCodigoEmpresa.getText().isEmpty()&&!txtNombre.getText().isEmpty())
        {
            //Obtenemos los valores de los JTextFields
            getValores();
                 if(tipoOperacion==Utilidades.GUARDAR)
                {
                   if(empresa.guardar())
                   {
                       JOptionPane.showMessageDialog(null, "Datos guardados con éxito");
                    
                       //Una vez que se guardadan los datos sellenan los JTextFields con los datos guardados
                       llenarCampos(); 
                       //Si se realizo todo correcto entonces realizado sera verdadero
                       realizado=true;
                       //Asignamos en falso las variables centinelas ya que todo debe quedar reseteado
                       //Para buscar nuevos cambios
                       realizoCambios=false;
                       eliminoLogo=false;
                   }
                }
                else if(tipoOperacion==Utilidades.ACTUALIZAR)
                {
                /*Si los datos se actualizaron y  "auxRutaAuxiliar"(se le asigna un valor en el metodo seleccionarArchivo()
                cuando seleccionamos un nuevo archivo o en el boton btnEliminarLogo)no esta vacia y  la ruta del logo nuevo es
                    diferente a la ruta del logo anterior entonces se elima el logo anterior*/
                    if(empresa.actualizar())
                    {
                       if((!auxRutaLogo.equals(empresa.getRutaLogo()) && !auxRutaLogo.equals("")))
                       eliminarArchivo(dirUsuario+auxRutaLogo);
                       JOptionPane.showMessageDialog(null, "Datos actualizados con exito");
                       //Actualizados los datos volvemos a llenar los JTextFields con los datos actualizados
                       llenarCampos();
                       
                       //Si se realizo todo correcto entonces realizado sera verdadero
                       realizado=true;
                       
                       //Asignamos en falso las variables centinelas ya que todo debe quedar reseteado
                       //Para buscar nuevos cambios
                       realizoCambios=false;
                       eliminoLogo=false;
                    }
                    else
                         JOptionPane.showMessageDialog(null, "Error al actualizar ");
                }
        }
        else
         {
            realizado=false;
            JOptionPane.showMessageDialog(null, "Los campo \"Nombre\" y \"Código\" son Obligatorios");
         }
      return realizado;
  }
    
    //Con este metodo removemos el logo anterior cuando se cambia a uno nuevo
  void eliminarArchivo(String rutaLogo){
       File archivo=new File(rutaLogo);
       //Verificamos que el archivo existe antes de borrarlo
       
        if(esArchivo(rutaLogo) && !rutaLogo.equals("") && rutaLogo!=null)
       {
            try
            {
                 archivo.delete();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error al actualizar el logo\n"+ e);  
            }      
       }
  }
    //Con este metodo enviaremos un mensaje de advertencia
    private void validacionSalir(){
        if(realizoCambios||eliminoLogo)
        {
          int opcion=JOptionPane.showConfirmDialog(null,"Los datos se modificaron.\n"
                                            + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
            if(opcion==JOptionPane.YES_OPTION)
            {
                if(guardar())
                {
                    
                }
                // dispose();
            }
            else if(opcion==JOptionPane.NO_OPTION)
            {
                //dispose();
            }
        }
        else
        {
            
        }
            //dispose();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarLogo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSubirLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane speDireccion;
    private javax.swing.JTextField txtCodigoEmpresa;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRtn;
    private javax.swing.JTextField txtRubro;
    private javax.swing.JTextField txtSlogan;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
