/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmsoft.Formularios;

import dmsoft.Clases.Entidades.Unidades;
import dmsoft.Clases.Entidades.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany_Hernandez
 */
public class IframeUnidades extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeCategoria
     */
    int tipoOperacion=Utilidades.NUEVO;
    Utilidades utilidades=new Utilidades();
    DefaultTableModel modeloUnidad;
     Unidades unidades=new Unidades();
    
    public IframeUnidades() {
        initComponents();
              //Eliminamos el border del JInternalFrame para que no nos muestre las opciones de arriba
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI(); 
        bi.setNorthPane(null);
        
        modeloTabla();
        unidades.obtenerDatos(tblUnidad, modeloUnidad, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        spneProveedores = new javax.swing.JScrollPane();
        tblUnidad = new javax.swing.JTable();
        panelIngresarDatos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spneExplicacion = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtAbreviatura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        panelBotones = new javax.swing.JPanel();
        btnNuevo1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setName("Unidades"); // NOI18N

        panelPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelBuscar.setBackground(new java.awt.Color(246, 246, 246));
        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true), "Realizar busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        panelBuscar.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/buscar26.png"))); // NOI18N
        jLabel7.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 7, 5, 0);
        panelBuscar.add(jLabel7, gridBagConstraints);

        txtBuscar.setBackground(new java.awt.Color(252, 252, 252));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 687;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 5, 15);
        panelBuscar.add(txtBuscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 67, 3, 49);
        panelPrincipal.add(panelBuscar, gridBagConstraints);

        spneProveedores.setPreferredSize(new java.awt.Dimension(452, 390));

        tblUnidad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tblUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spneProveedores.setViewportView(tblUnidad);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 67, 3, 49);
        panelPrincipal.add(spneProveedores, gridBagConstraints);

        panelIngresarDatos.setBackground(new java.awt.Color(246, 246, 246));
        panelIngresarDatos.setPreferredSize(new java.awt.Dimension(368, 170));
        panelIngresarDatos.setRequestFocusEnabled(false);
        panelIngresarDatos.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Unidad de medida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelIngresarDatos.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel10, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 0);
        panelIngresarDatos.add(txtNombre, gridBagConstraints);

        spneExplicacion.setBorder(null);
        spneExplicacion.setPreferredSize(new java.awt.Dimension(112, 300));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea2.setColumns(9);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(2);
        jTextArea2.setTabSize(5);
        jTextArea2.setText("Cuando el \"Estado\" es Inactivo, la unidad de medida no estará disponible para seleccionar cuando guardes un producto. ");
        spneExplicacion.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(36, 21, 28, 16);
        panelIngresarDatos.add(spneExplicacion, gridBagConstraints);

        jLabel11.setBackground(new java.awt.Color(151, 196, 242));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/unidadMedida26.png"))); // NOI18N
        jLabel11.setText("Unidades de medida");
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(55, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelIngresarDatos.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        panelIngresarDatos.add(jLabel12, gridBagConstraints);

        jScrollPane3.setBorder(null);

        txtNota.setBackground(new java.awt.Color(252, 252, 252));
        txtNota.setColumns(20);
        txtNota.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtNota.setLineWrap(true);
        txtNota.setRows(3);
        txtNota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jScrollPane3.setViewportView(txtNota);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 0);
        panelIngresarDatos.add(jScrollPane3, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Abreviatura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel1, gridBagConstraints);

        txtAbreviatura.setBackground(new java.awt.Color(252, 252, 252));
        txtAbreviatura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtAbreviatura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtAbreviatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAbreviaturaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 0);
        panelIngresarDatos.add(txtAbreviatura, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("* Campos obligatorios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        panelIngresarDatos.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        panelIngresarDatos.add(jLabel4, gridBagConstraints);

        cbxEstado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEstadoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 19, 0, 0);
        panelIngresarDatos.add(cbxEstado, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 67, 3, 49);
        panelPrincipal.add(panelIngresarDatos, gridBagConstraints);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(250, 250, 250));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        panelBotones.setPreferredSize(new java.awt.Dimension(120, 23));
        panelBotones.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        btnNuevo1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregar40.png"))); // NOI18N
        btnNuevo1.setText("Nuevo");
        btnNuevo1.setToolTipText("Agregar nuevo empleado");
        btnNuevo1.setBorder(null);
        btnNuevo1.setContentAreaFilled(false);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.setFocusPainted(false);
        btnNuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo1.setPreferredSize(new java.awt.Dimension(70, 75));
        btnNuevo1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregar44.png"))); // NOI18N
        btnNuevo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        panelBotones.add(btnNuevo1);

        btnGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar40.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar empleado");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar44.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar40.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita un empleado");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar44.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEditar);

        btnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/delete40.png"))); // NOI18N
        btnRetornar.setText("Eliminar");
        btnRetornar.setToolTipText("Sale de la pestaña");
        btnRetornar.setBorderPainted(false);
        btnRetornar.setContentAreaFilled(false);
        btnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetornar.setFocusPainted(false);
        btnRetornar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetornar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnRetornar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/delete44.png"))); // NOI18N
        btnRetornar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        panelBotones.add(btnRetornar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        unidades.obtenerDatos(tblUnidad, modeloUnidad, txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        if(!utilidades.isChanged())
        {
            tipoOperacion=Utilidades.NUEVO;
            resetFields();
        }
        else
        {
            int opcion=JOptionPane.showConfirmDialog(null,"Esta procesando datos y realizado camios.\n"
                + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(opcion==JOptionPane.YES_OPTION)
            {
                //Si se guardan los datos se reseatean todos los
                if(guardarDatos())
                {
                    tipoOperacion=Utilidades.NUEVO;
                    resetFields();
                    unidades.obtenerDatos(tblUnidad, modeloUnidad, "");
                }

            }
            else if(opcion==JOptionPane.NO_OPTION)
            {
                //Reseteamos la operacion a default
                resetFields();
            }
        }
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if(guardarDatos())
        {
            resetFields();
            unidades.obtenerDatos(tblUnidad, modeloUnidad, "");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //verificamos que no se este realizando otra operacion
        if(tipoOperacion==Utilidades.NUEVO||tipoOperacion==Utilidades.EDITAR)
        {
            //Validamos que se seleccione un campo
            if(tblUnidad.getSelectedRow()>=0)
            {
                if(!utilidades.isChanged())
                {
                    tipoOperacion=Utilidades.EDITAR;
                    unidades.setIdUnidad((Integer)tblUnidad.getValueAt(tblUnidad.getSelectedRow(), 0));
                    txtNombre.setText(tblUnidad.getValueAt(tblUnidad.getSelectedRow(), 1).toString());
                    txtAbreviatura.setText(tblUnidad.getValueAt(tblUnidad.getSelectedRow(), 2).toString());
                    cbxEstado.setSelectedItem(tblUnidad.getValueAt(tblUnidad.getSelectedRow(), 3).toString());
                    txtNota.setText(tblUnidad.getValueAt(tblUnidad.getSelectedRow(), 4).toString());
                }
                else
                {
                    int opcion=JOptionPane.showConfirmDialog(null,"Esta procesando datos y realizado camios.\n"
                        + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(opcion==JOptionPane.YES_OPTION)
                    {
                        //Si se guardan los datos se reseatean todos los campos y se rellena la tabla
                        if(guardarDatos())
                        {
                            resetFields();
                            unidades.obtenerDatos(tblUnidad, modeloUnidad, "");
                        }

                    }
                    else if(opcion==JOptionPane.NO_OPTION)
                    {
                        //Reseteamos la operacion a default
                        resetFields();
                    }
                }
            }
            else
            JOptionPane.showMessageDialog(this, "Debe seleccionar una categoría para editar");

        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        if(tblUnidad.getSelectedRow()>=0)
        {
            int respuesta=unidades.eliminar((Integer)tblUnidad.getValueAt(tblUnidad.getSelectedRow(),0));

            if(respuesta==Utilidades.REALIZADO)
            {
                JOptionPane.showMessageDialog(null,"Proveedor eliminado con éxito");
                unidades.obtenerDatos(tblUnidad, modeloUnidad, "");
                resetFields();
            }
            else if(respuesta==Utilidades.TIENE_RELACION)
            JOptionPane.showMessageDialog(null,"El proveeodor no se puede elimar porque tiene\n una relación en la tabla productos");

        }
        else
        JOptionPane.showMessageDialog(null, "Debe seleccionar de la tabla al proveedor que desea borrar");

    }//GEN-LAST:event_btnRetornarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtAbreviaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbreviaturaKeyReleased
         utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtAbreviaturaKeyReleased

    private void cbxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEstadoItemStateChanged
       if(tipoOperacion==Utilidades.EDITAR)
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_cbxEstadoItemStateChanged

    //Este metodo es para darle diseño al modelo de la tabla 
   private  void modeloTabla(){
      //Creamos un arreglo de Strings para los encabezados de nuestra tabla
    String encabezados[]= {"ID", "Nombre unidad", "Abreviatura","Estado","Nota"};
    //Creamos un modelo para nuestros arreglo para los encabezados
   modeloUnidad=new DefaultTableModel(null,encabezados){
       /*Creamos un arreglo de tipos para nuestra tabla, dicho arreglo es paralelo con el nombre 
        arreglo de nombres del encabezado*/
        Class tipos[]={
                Integer.class,
                String.class, 
                String.class,
                 String.class, 
                String.class};
        //Sobre escribimos el metodo getColumIndex para que devuelva la posicion de nuestro arreglo de tipos
        @Override
         public Class getColumnClass(int index){
            return tipos[index];
         }
         //Tambien sobre escribimos el metodo que permite editar las celdas de la tabla
        @Override
         public boolean isCellEditable(int rowIndex,int columnIndex){
             return false;
         }
       };
    //Agregamos nuestro modelo a la tabla
     tblUnidad.setModel(modeloUnidad);
        //Creamos un arreglo con las medidas fijos predeterminados de la tabla para cada celda
      int ancho[]={70,150,80,120,400};
      for(int i=0;i<tblUnidad.getColumnCount();i++)
      {
          tblUnidad.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
          tblUnidad.getColumnModel().getColumn(i).setResizable(false);
      }
     utilidades.setTableHeader(tblUnidad);
     tblUnidad.setRowHeight(20);
     }
 //Este metodo se encarga de deicidir que tipo de operacion se realizara. Si es Guardar o Actualizar
   private boolean realizarOperacion(int tipo){
       boolean realizado=false;
       switch(tipo)
       {
            case Utilidades.NUEVO:
                //llenamos la variables de la clase empleados con los valores del campo de texto
                //que luego seran enviadas en el metodo guardar o actualizar
                setDatos();
                //Luego utilizamos las variables para mandar a llamar al metodo guardar
                if(unidades.guardar())
                  realizado=true;  
            break;
            case Utilidades.EDITAR:
                setDatos();
                if(unidades.actualizar())
                    realizado=true;
            break;
       }
       return realizado;
   }
   //Con este metodo asignamos valores a las variables de la clase Proveedor
   private void setDatos(){
       unidades.setUnidad(txtNombre.getText());
       unidades.setAbreviatura(txtAbreviatura.getText());
       unidades.setEstado(cbxEstado.getSelectedItem().toString());
       unidades.setNota(txtNota.getText());
   }
   
   //Con este metodo guardamos los datos y los actualizamos
   private boolean guardarDatos(){
       boolean realizado=false;
       if(!txtNombre.getText().isEmpty()){
           realizado=realizarOperacion(tipoOperacion);
       }
       else
           JOptionPane.showMessageDialog(null,"El campo de \"Nombre\" no puede ser vacio.");
       
       return realizado;
   }
   //Este metodo reseta todos los campos
   private void resetFields(){
    tblUnidad.clearSelection();
    tipoOperacion=Utilidades.NUEVO;
    utilidades.setChanged(false);
    txtNombre.setText("");
    txtAbreviatura.setText("");
    cbxEstado.setSelectedIndex(0);
    txtNota.setText("");
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelIngresarDatos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane spneExplicacion;
    private javax.swing.JScrollPane spneProveedores;
    private javax.swing.JTable tblUnidad;
    private javax.swing.JTextField txtAbreviatura;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
}
