/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dmsoft.Formularios;

import dmsoft.Clases.Entidades.Proveedor;
import dmsoft.Clases.Entidades.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany_Hernandez
 */
public class IframeProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form IframeProveedor
     */
    DefaultTableModel modeloProveedor;
    Utilidades utilidades= new  Utilidades();
    Proveedor proveedor=new Proveedor();
    
    int tipoOperacion=Utilidades.NUEVO;
    public IframeProveedor() {
        initComponents();
          
      //Eliminamos el border del JInternalFrame para que no nos muestre las opciones de arriba
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI(); 
        bi.setNorthPane(null);
        
        //Asignamos un modelo a la tabla
        modeloTabla();
        
        proveedor.obtenerDatos(tblProveedores, modeloProveedor, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        spneProveedores = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        panelIngresarDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRepresentante = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelBotones1 = new javax.swing.JPanel();
        btnNuevo1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBorder(null);
        setName("Proveedor"); // NOI18N

        panelPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelBuscar.setBackground(new java.awt.Color(246, 246, 246));
        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Realizar busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/buscar26.png"))); // NOI18N
        jLabel7.setText("Buscar");

        txtBuscar.setBackground(new java.awt.Color(252, 252, 252));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 3, 24);
        panelPrincipal.add(panelBuscar, gridBagConstraints);

        spneProveedores.setPreferredSize(new java.awt.Dimension(452, 390));

        tblProveedores.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spneProveedores.setViewportView(tblProveedores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        panelPrincipal.add(spneProveedores, gridBagConstraints);

        panelIngresarDatos.setBackground(new java.awt.Color(246, 246, 246));
        panelIngresarDatos.setPreferredSize(new java.awt.Dimension(368, 170));
        panelIngresarDatos.setRequestFocusEnabled(false);
        panelIngresarDatos.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelIngresarDatos.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Representante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        panelIngresarDatos.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Producto o servicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelIngresarDatos.add(jLabel6, gridBagConstraints);

        txtNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panelIngresarDatos.add(txtNombre, gridBagConstraints);

        txtRepresentante.setBackground(new java.awt.Color(252, 252, 252));
        txtRepresentante.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtRepresentante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRepresentanteKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        panelIngresarDatos.add(txtRepresentante, gridBagConstraints);

        txtTelefono.setBackground(new java.awt.Color(252, 252, 252));
        txtTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        panelIngresarDatos.add(txtTelefono, gridBagConstraints);

        txtCorreo.setBackground(new java.awt.Color(252, 252, 252));
        txtCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        panelIngresarDatos.add(txtCorreo, gridBagConstraints);

        txtProducto.setBackground(new java.awt.Color(252, 252, 252));
        txtProducto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        txtProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        panelIngresarDatos.add(txtProducto, gridBagConstraints);

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(112, 300));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(9);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(5);
        jTextArea1.setText("Para realizar una busqueda puede escribir lo que desea buscar en el campo buscar.");
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 21, 28, 16);
        panelIngresarDatos.add(jScrollPane1, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(151, 196, 242));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/proveedor26.png"))); // NOI18N
        jLabel1.setText("Proveedores");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(55, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        panelIngresarDatos.add(jLabel1, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*Obligatorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        panelIngresarDatos.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 3, 24);
        panelPrincipal.add(panelIngresarDatos, gridBagConstraints);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        panelBotones1.setBackground(new java.awt.Color(250, 250, 250));
        panelBotones1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        panelBotones1.setPreferredSize(new java.awt.Dimension(120, 23));
        panelBotones1.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        btnNuevo1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregarDatos40.png"))); // NOI18N
        btnNuevo1.setText("Nuevo proveedor");
        btnNuevo1.setToolTipText("Agregar nuevo empleado");
        btnNuevo1.setBorder(null);
        btnNuevo1.setContentAreaFilled(false);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.setFocusPainted(false);
        btnNuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo1.setPreferredSize(new java.awt.Dimension(70, 75));
        btnNuevo1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/agregarDatos44.png"))); // NOI18N
        btnNuevo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        panelBotones1.add(btnNuevo1);

        btnGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar40.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar empleado");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/guardar44.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBotones1.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar40.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita un empleado");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/editar44.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones1.add(btnEditar);

        btnEliminar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/delete40.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Sale de la pestaña");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(70, 75));
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/dmsoft/Imagenes/delete44.png"))); // NOI18N
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelBotones1.add(btnEliminar);

        getContentPane().add(panelBotones1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
    if(!utilidades.isChanged())
        {
             tipoOperacion=Utilidades.NUEVO;
               resetFields();
        }
    else
    {
        int opcion=JOptionPane.showConfirmDialog(null,"Esta procesando datos y realizado camios.\n"
                                           + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opcion==JOptionPane.YES_OPTION)
         {
             //Si se guardan los datos se reseatean todos los 
                if(guardarDatos())
                {
                 tipoOperacion=Utilidades.NUEVO;
                  resetFields();
                  proveedor.obtenerDatos(tblProveedores, modeloProveedor, "");
                }
                  
              }
              else if(opcion==JOptionPane.NO_OPTION)
              {
                  //Reseteamos la operacion a default
                  resetFields();
              }
    }       
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

             if(guardarDatos())
             {
               resetFields();
               proveedor.obtenerDatos(tblProveedores, modeloProveedor, "");
             }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       //verificamos que no se este realizando otra operacion
      if(tipoOperacion==Utilidades.NUEVO||tipoOperacion==Utilidades.EDITAR)
      {
          //Validamos que se seleccione un campo
          if(tblProveedores.getSelectedRow()>=0)
          {
                if(!utilidades.isChanged())
                {
                    tipoOperacion=Utilidades.EDITAR;
                    proveedor.setIdProveedor((Integer)tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 0));
                    txtNombre.setText(tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 1).toString());
                    txtRepresentante.setText(tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 2).toString());
                    txtTelefono.setText(tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 3).toString());
                    txtCorreo.setText(tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 4).toString());
                    txtProducto.setText(tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 5).toString());
                }
                else
                {
                 int opcion=JOptionPane.showConfirmDialog(null,"Esta procesando datos y realizado camios.\n"
                                              + "¿Desea guardar los cambios?","Salir",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                       if(opcion==JOptionPane.YES_OPTION)
                        {
                            //Si se guardan los datos se reseatean todos los 
                               if(guardarDatos())
                               {
                                 //reseteamso los valores a por defecto
                                 resetFields();
                                 //volvemos a llenar los datos de la tabla
                                proveedor.obtenerDatos(tblProveedores, modeloProveedor, "");
                               }

                        }
                       else if(opcion==JOptionPane.NO_OPTION)
                       {
                           //Reseteamos la operacion a default
                           resetFields();
                       }
                }
              }       
              else
              JOptionPane.showMessageDialog(this, "Debe seleccionar una proveedor para editar");

        }
          
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     if(tblProveedores.getSelectedRow()>=0)
     {
         int respuesta=proveedor.eliminar((Integer)tblProveedores.getValueAt(tblProveedores.getSelectedRow(),0));
         
         if(respuesta==Utilidades.REALIZADO)
         {
             JOptionPane.showMessageDialog(null,"Proveedor eliminado con éxito");
             proveedor.obtenerDatos(tblProveedores, modeloProveedor, "");
             resetFields();
         }
         else if(respuesta==Utilidades.TIENE_RELACION)
             JOptionPane.showMessageDialog(null,"El proveeodor no se puede elimar porque tiene\n una relación en la tabla productos");
                  
     }
     else 
         JOptionPane.showMessageDialog(null, "Debe seleccionar de la tabla al proveedor que desea borrar");
 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        proveedor.obtenerDatos(tblProveedores, modeloProveedor, txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtRepresentanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepresentanteKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtRepresentanteKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyReleased
        utilidades.setChanged(utilidades.onChange(evt));
    }//GEN-LAST:event_txtProductoKeyReleased
//Este metodo es para darle diseño al modelo de la tabla 
   private  void modeloTabla(){
      //Creamos un arreglo de Strings para los encabezados de nuestra tabla
    String encabezados[]= {"ID", "Nombre proveedor", "Representante", "Teléfono", 
                           "Correo", "Producto o servicio"};
    //Creamos un modelo para nuestros arreglo para los encabezados
   modeloProveedor=new DefaultTableModel(null,encabezados){
       /*Creamos un arreglo de tipos para nuestra tabla, dicho arreglo es paralelo con el nombre 
        arreglo de nombres del encabezado*/
        Class tipos[]={
                Integer.class,
                String.class, 
                String.class,
                String.class,
                String.class,
                String.class,
                String.class};
        //Sobre escribimos el metodo getColumIndex para que devuelva la posicion de nuestro arreglo de tipos
        @Override
         public Class getColumnClass(int index){
            return tipos[index];
         }
         //Tambien sobre escribimos el metodo que permite editar las celdas de la tabla
        @Override
         public boolean isCellEditable(int rowIndex,int columnIndex){
             return false;
         }
       };
    //Agregamos nuestro modelo a la tabla
     tblProveedores.setModel(modeloProveedor);
        //Creamos un arreglo con las medidas fijos predeterminados de la tabla para cada celda
      int ancho[]={50,170,180,120,140,200};
      for(int i=0;i<tblProveedores.getColumnCount();i++)
      {
          tblProveedores.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
          tblProveedores.getColumnModel().getColumn(i).setResizable(false);
      }
     utilidades.setTableHeader(tblProveedores);
     tblProveedores.setRowHeight(20);
     }
 //Este metodo se encarga de deicidir que tipo de operacion se realizara. Si es Guardar o Actualizar
   private boolean realizarOperacion(int tipo){
       boolean realizado=false;
       switch(tipo)
       {
            case Utilidades.NUEVO:
                //llenamos la variables de la clase empleados con los valores del campo de texto
                //que luego seran enviadas en el metodo guardar o actualizar
                setDatos();
                //Luego utilizamos las variables para mandar a llamar al metodo guardar
                if(proveedor.guardar())
                  realizado=true;  
            break;
            case Utilidades.EDITAR:
                setDatos();
                if(proveedor.actualizar())
                    realizado=true;
            break;
       }
       return realizado;
   }
   //Con este metodo asignamos valores a las variables de la clase Proveedor
   private void setDatos(){
       proveedor.setNombre(txtNombre.getText());
       proveedor.setRepresentante(txtRepresentante.getText());
       proveedor.setTelefono(txtTelefono.getText());
       proveedor.setCorreo(txtCorreo.getText());
       proveedor.setProducto(txtProducto.getText());
   }
   
   //Con este metodo guardamos los datos y los actualizamos
   private boolean guardarDatos(){
       boolean realizado=false;
       if(!txtNombre.getText().isEmpty()){
           realizado=realizarOperacion(tipoOperacion);
       }
       else
           JOptionPane.showMessageDialog(null,"El campo de \"Nombre\" no puede ser vacio.");
       
       return realizado;
   }
   //Este metodo reseta todos los campos
   private void resetFields(){
    tblProveedores.clearSelection();
    tipoOperacion=Utilidades.NUEVO;
    utilidades.setChanged(false);
      txtNombre.setText("");
      txtRepresentante.setText("");
      txtTelefono.setText("");
      txtCorreo.setText("");
      txtProducto.setText("");
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelBotones1;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelIngresarDatos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane spneProveedores;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
